### ISSUE TITLE
Ethical Concern about the treatment of GPU's

### ISSUE THREAD

**Issue by tacalvin** [willshiao/sdhacks-2018#1]
I demand better treatment of GPU's

**Comment by willshiao** [comment]
We're paying them up to $2/hour.

**Comment by tacalvin** [comment]
That is pathetic. I demand $15/hr and shift's no longer than 8hrs.

**Comment by willshiao** [comment]
Please pay attention to your spelling and grammar. I cannot read your argument. Therefore, it is wrong.
